name: .NET

on:
  push:
    branches: [ "mainn" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Prepare tag name
      id: create_tag_name
      run: |
        echo ::set-output name=TAG_NAME::$( echo "1" | tr -d '"')
        
    - name: Create the Github Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: v${{ steps.create_tag_name.outputs.TAG_NAME }}
        tag_name: v${{ steps.create_tag_name.outputs.TAG_NAME }}
        body: CHANGELOG
      env:
        GITHUB_TOKEN: ${{ github.token }}
