name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Fetch wallet version
      id: versionResponse
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://85.218.136.241:5555/version'
        method: 'GET'
        
    - name: Show Response
      run: |
        echo ${{ steps.versionResponse.outputs.response }}
