name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Fetch version
      id: versionResponse
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://releases.discreet.net/versions/wallet'
        method: 'GET'
        
    - name: Echo version
      run: cat Application/WPF.csproj
      
    - name: Prepare versions string
      id: version_string
      run: echo "::set-output name=TAG_NAME::$( echo ${{ steps.versionResponse.outputs.response }} | tr -d '"')"
      shell: bash
      
    - name: Edit version in csproj
      run: sed -i 's/<Version>.*<\/Version>/<Version>${{ steps.version_string.outputs.TAG_NAME }}<\/Version>/g' Application/WPF.csproj
  
    - name: Echo version
      run: cat Application/WPF.csproj
      
    - name: Push it
      run: |
        git config user.name ghdiscreet
        git config user.email github@discreet.net
        git remote set-url origin https://${{ secrets.GAT }}@github.com/rickifunk/versioning-test.git/
        git add Application/WPF.csproj
        git commit -m "Edited version in WPF.csproj"
        git fetch origin main
        git push origin HEAD:main
