name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Echo version
      run: cat Application/WPF.csproj
      
    - name: Edit version in csproj
      run: sed -i 's/<Version>.*<\/Version>/<Version>1.0.3<\/Version>/g' Application/WPF.csproj
  
    - name: Echo version
      run: cat Application/WPF.csproj
      
    - name: Push it
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add Application/WPF.csproj
        git commit -m "Edited version in WPF.csproj"
        git fetch origin main
        git push origin HEAD:main
