name: Patch pipeline

on:
  push:
    branches: [ "patch/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: | 
        cd Application/
        dotnet restore
      
    - name: Build
      run: |
        cd Application/
        dotnet build --no-restore
        
    - name: Increment patch version
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://85.218.136.241:5555/version/patch'
        method: 'POST'
