name: staging 

on:
  pull_request:
    types: [closed]
    branches: [ "staging" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Doing work
      run: echo "Doing the work"
      if: github.event.pull_request.merged == true
