name: staging 
 
on:
  pull_request:
    types: [closed]
    branches: [ "staging" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      run: exit(1)
      if: github.event.pull_request.merged == false

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Doing work
      run: echo "Doing the work"
