name: staging 
      
on:
  pull_request:
    types: [closed]
    branches: [ "staging" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Display ref
      id: set_ref
      run: |
       ref="${{ github.head_ref }}"
       ref_short=${ref%%/*}
       if [ "$ref_short" == "patch" ]; then
          echo "::set-output name=IS_PATCH::$(echo true)"
       else
          echo "::set-output name=IS_PATCH::$(echo false)"
       fi
       
       if [ "$ref_short" == "feature" ]; then
          echo "::set-output name=IS_FEATURE::$(echo true)"
       else
          echo "::set-output name=IS_FEATURE::$(echo false)"
       fi
      if: ${{ github.event.pull_request.merged == true }} 
    
    - name: Patch work
      run: | 
        echo "Doing the patch work"
      if: ${{ github.event.pull_request.merged == true && steps.set_ref.outputs.IS_PATCH == true }} 

    - name: Feature work
      run: | 
        echo "Doing the feature work"
      if: ${{ github.event.pull_request.merged == true && steps.set_ref.outputs.IS_FEATURE == true }} 
